// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbraerdaczxnawbsfbgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicmFlcmRhY3p4bmF3YnNmYmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjUyMTYsImV4cCI6MjA2MDA0MTIxNn0.Qg-Xoz8hsFX3YRUMBKgTi15jnVPoavtSFC4zCMNYedo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);